name: build module

on:
  push:
    branches: master
    paths-ignore: 
      - '**.md'
  workflow_dispatch:

env:
  MODULE_NAME: 'KSUToolkit'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: master

      - name: Grab SStrip from ELFKickers
        run: |
          curl -L https://www.muppetlabs.com/~breadbox/pub/software/ELFkickers-3.2.tar.gz -o sstrip.tar.gz
          tar xf sstrip.tar.gz
          make -C ELFkickers-3.2 sstrip
          cp ELFkickers-3.2/sstrip/sstrip .

      - name: Compile via ZigCC 
        run: |
          echo "aarch64"
          pwd
          mkdir bin

          chmod +x sstrip

          cd src
          zig cc -target aarch64-linux -std=c11 -s -Oz -static -Wl,--gc-sections,-z,norelro -fno-unwind-tables -Wl,--entry=__start -flto -fmerge-all-constants -Wno-unknown-attributes toolkit.c -o ../bin/toolkit-arm64
          zig cc -target arm-linux -std=c11 -s -Oz -static -Wl,--gc-sections,-z,norelro -fno-unwind-tables -Wl,--entry=__start -flto -fmerge-all-constants -Wno-unknown-attributes toolkit.c -o ../bin/toolkit-arm
          
          cd ../bin

          wc -c Toolkit-*
          
          ../sstrip -z Toolkit-arm64
          ../sstrip -z Tolkit-arm

          wc -c Toolkit-*
          file Toolkit-*
          mkdir -p ../module/bin
          mv Toolkit-* ../module/bin

      - name: Build WebUI
        run: |
          cd webui
          npm ci
          npm run build

      - name: Update Version Code
        run: sed -i 's/^versionCode=.*/versionCode=${{ github.run_number }}/' module/module.prop

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ env.MODULE_NAME }}-${{ github.run_number }}
          path: module/
